Add a KeepAlive on connection between layer and agent
metalbear-co/mirrord pull request #104
Opened 2022-06-01 21:40 UTC by infiniteregrets

Closes #63. The layer sends a ping to the agent pod and the pod responds back with a pong.

2022-06-01 21:42 UTC, infiniteregrets commented
Todo: currently ping works just fine as seen in the logs, but pong is never received.

2022-06-02 05:13 UTC, aviramha requested changes

2022-06-02 05:13 UTC, aviramha commented on mirrord-layer/src/lib.rs
> +    loop {
This needs to be in the timeout section of the select, also we need that when it occurs we check if last ping was pongd or not

2022-06-02 05:13 UTC, aviramha commented on mirrord-protocol/src/codec.rs
> +pub struct PingMessage {
redundant

2022-06-02 18:43 UTC, eyalb181 requested changes
LGTM, just update the CHANGELOG.

2022-06-02 20:53 UTC, eyalb181 requested changes

2022-06-02 22:16 UTC, infiniteregrets commented on CHANGELOG.md
> +- Added a keep-alive to keep the agent-pod from exiting, closes [#63](https://github.com/metalbear-co/mirrord/issues/63)
done, thanks

2022-06-03 09:10 UTC, eyalb181 approved these changes

2022-06-03 09:12 UTC, eyalb181 approved these changes

2022-06-03 10:16 UTC, aviramha approved these changes

2022-06-03 10:44 UTC, merged