Add hook for recvfrom
metalbear-co/mirrord pull request #1385
Opened 2023-05-05 17:45 UTC by infiniteregrets

Added hook for recvfrom to provide the caller with the original address it expects in some flows. This was necessary because of node dependency called c-ares for performing async DNS queries which expects original address as can be seen here:

```c
#ifdef HAVE_RECVFROM
        else if (!same_address(&from.sa, &server->addr))
          /* The address the response comes from does not match the address we
           * sent the request to. Someone may be attempting to perform a cache
           * poisoning attack. */
          break;
#endif
```

2023-05-05 18:02 UTC, meowjesty requested changes
Maybe add an integration test for this issue?

2023-05-05 20:53 UTC, meowjesty requested changes
Small nit.

2023-05-05 20:53 UTC, meowjesty commented on tests/node-e2e/outgoing/test_outgoing_traffic_original_address.mjs
> +    console.log(err);
```suggestion
    console.error(err);
```

2023-05-06 15:53 UTC, eyalb181 approved these changes

2023-05-06 16:02 UTC, merged