Tmp dir fs ops
metalbear-co/mirrord pull request #1406
Opened 2023-05-11 11:38 UTC by t4lz

#1403

2023-05-11 11:51 UTC, aviramha reviewed
Overall comment - I think the implementation can be that you just edit the original string, as it will always be less characters. It will make the implementation easier.

2023-05-11 11:51 UTC, aviramha commented on mirrord/layer/src/common.rs
> +lazy_static! {
put it in `sip` crate so we'll also have it only on macOS

2023-05-11 12:55 UTC, t4lz commented
> just edit the original string

What do you mean? This is already how it's done.

2023-05-11 12:57 UTC, aviramha commented
> > just edit the original string
> 
> What do you mean? This is already how it's done.

Aren't you creating a new string then replacing the ptr?

2023-05-11 12:58 UTC, aviramha commented
> > just edit the original string
> 
> What do you mean? This is already how it's done.

Oops. Missed that

2023-05-11 13:01 UTC, aviramha commented
You should check if the path is of the binary itself, then we should leave it as is.
I wouldn't add a bypass for it, but just change it as part of checked into without changing the behavior - maybe do a bypass if it's that path though

2023-05-11 13:52 UTC, aviramha commented
I agree we should bypass on this case, just not a new case of bypass

2023-05-11 14:47 UTC, t4lz commented
> I agree we should bypass on this case, just not a new case of bypass

Oh, I see. But I use this bypass variant to pass back the new pointer. How should I do it then?

2023-05-11 14:49 UTC, aviramha commented
> > I agree we should bypass on this case, just not a new case of bypass
> 
> Oh, I see. But I use this bypass variant to pass back the new pointer. How should I do it then?

In the checked into?

2023-05-11 15:37 UTC, t4lz commented
> In the checked into?

I am returning a `Bypass` with a the new `*const c_char` from `checked_into` if original path is in our dir. How should I do that without introducing a new variant of `Bypass`?

2023-05-11 16:23 UTC, aviramha commented
> > In the checked into?
> 
> I am returning a `Bypass` with a the new `*const c_char` from `checked_into` if the original path is in our dir. How should I do that without introducing a new variant of `Bypass`?

I thought `checked_into` requires `self` and not `&self` (because Into does, my bad).

2023-05-12 16:37 UTC, infiniteregrets commented on mirrord/layer/src/common.rs
> +}
Can we not use https://docs.rs/once_cell/latest/once_cell/sync/struct.Lazy.html here

2023-05-15 12:55 UTC, infiniteregrets requested changes

2023-05-15 12:55 UTC, infiniteregrets commented on mirrord/auth/Cargo.toml
>  rand = { version = "0.8", optional = true }
same

2023-05-15 12:55 UTC, infiniteregrets commented on Cargo.toml
no need of these

2023-05-16 10:53 UTC, merged