Dynamic target pause
metalbear-co/mirrord pull request #1407
Opened 2023-05-11 11:43 UTC by Razz4780

2023-05-11 13:56 UTC, Razz4780 commented
> > this PR is not `draft` only to enable CI
> 
> You can allow the repo's workflows to run in your fork, then you can see the CI runs in your [fork's Actions tab](https://github.com/Razz4780/mirrord/actions). We can also just enable the workflow for drafts, bring it to discussion with the team if you think it should be enabled.

Oh, that's cool. Didn't know about it, thanks!

2023-05-15 15:59 UTC, Razz4780 commented on mirrord/agent/src/main.rs
> +        };
I'd leave this as it is, working with both futures and `Result`s/`Option`s is always pretty verbose

2023-05-15 16:02 UTC, Razz4780 commented on mirrord/cli/src/execution.rs
> +    async fn get_remote_env(
Did you mean `tracing::instrument`? It seems there's no use of that across the `cli` crate

2023-05-15 16:35 UTC, meowjesty commented on mirrord/cli/src/execution.rs
> +    async fn get_remote_env(
Yeah.

Oh snap, should we start using it there?

Anyway, suggestion remains for things outside `cli` crate.

2023-05-15 17:18 UTC, Razz4780 commented
> Some minor stuff.
> 
> As I understand this feature is still ongoing some discussion if it should be agent or operator?

The final decision is to move the refcount logic to the operator, converted to draft

2023-05-19 14:15 UTC, meowjesty requested changes
From what I understand, the part of multi client pause is now handled in the operator (or will be, not sure if it's supported there yet)?

:play_or_pause_button:

2023-05-19 14:15 UTC, meowjesty commented on mirrord/agent/src/main.rs
> +    /// Handle to the target container if there is one.
I would keep the docs justifying why this is an `Option`.

2023-05-19 14:15 UTC, meowjesty commented on mirrord/agent/src/main.rs
> +        let handle = match container {
As far as I can see, we don't use the original `container` after this, so why not:

```suggestion
        let container = match container {
```

2023-05-22 07:42 UTC, Razz4780 commented on mirrord/agent/src/container_handle.rs
> +    paused: RwLock<bool>,
Using `RwLock` here was just much more simple than figuring out how to handle weird scenarios only with an atomic bool. Like: one user requests pause and other user requests unpause at the same time, two users request pause but the pause request fails, etc.

2023-05-22 13:31 UTC, meowjesty approved these changes
:bear: :+1:

2023-05-22 16:42 UTC, merged