Handle openat/open relative paths
metalbear-co/mirrord pull request #151
Opened 2022-06-15 14:37 UTC by infiniteregrets

Following changes have been made in the pull request:
- if open is called with a relative path, we just propagate that call to libc otherwise the call goes to agent 
- if openat is called with an absolute path or `AT_FDCWD` then we send the call to open otherwise we check our hashmap for existing descriptors if we dont have a dirfd we make the libc call 
- a test to verify read-write file operation

2022-06-16 07:03 UTC, aviramha requested changes

2022-06-16 07:03 UTC, aviramha commented on tests/python-e2e/ops.py
> +    def test_read_write_family(self):
how does this test ensure it's running remotely?

2022-06-16 07:03 UTC, aviramha commented on mirrord-agent/src/file.rs
> +pub struct RemoteFile {
why do we need it..?

2022-06-16 07:03 UTC, aviramha commented on mirrord-agent/src/file.rs
> +pub struct RemoteFile {
when openat is used, we just need a different object for it, but that object doesn't need a path either..

2022-06-17 15:30 UTC, eyalb181 commented on mirrord-agent/src/file.rs
> +                        if metadata.is_dir() {
Stylewise, I would suggest
```suggestion
                        let value = if metadata.is_dir() { RemoteFile::Directory(path)} else {RemoteFile::File(file)};
                        self.open_files.insert(fd, value);
```

2022-06-17 15:30 UTC, eyalb181 commented on mirrord-agent/src/file.rs
> +pub(crate) fn get_fd() -> usize {
Might be clearer to call this generate_fd, get implies you're retrieving an existing value

2022-06-18 10:21 UTC, eyalb181 commented on mirrord-agent/src/file.rs
> +        .map_err(|fail| {
Why isn't this inside the if clause (rather than chained to the whole if/else)?

2022-06-20 14:18 UTC, eyalb181 approved these changes

2022-06-20 14:19 UTC, aviramha approved these changes

2022-06-20 14:19 UTC, merged