Allow Forcfully to unlock PortLock on Operator
metalbear-co/mirrord pull request #1537
Opened 2023-06-11 15:49 UTC by DmitryDodzin

2023-06-11 18:38 UTC, eyalb181 requested changes
Few initial comments

2023-06-11 18:38 UTC, eyalb181 commented on mirrord-schema.json
> +      "description": "(Operator Only): Allows overiding port locks\n\nCan be set to either `\"continue\"` (default) or `\"override\"`.\n\n- `\"continue\"`: Continue with normal execution - `\"overrid
```suggestion
      "description": "(Operator Only): Allows overriding port locks\n\nCan be set to either `\"continue\"` (default) or `\"override\"`.\n\n- `\"continue\"`: Continue with normal execution - `\"override\"`: If port lock detected then override it with new lock and force close the original locking connection.",
```

2023-06-11 18:38 UTC, eyalb181 commented on mirrord-schema.json
> +      "description": "(Operator Only): Allows overiding port locks\n\nCan be set to either `\"continue\"` (default) or `\"override\"`.\n\n- `\"continue\"`: Continue with normal execution - `\"overrid
Also, default should be abort with an error message

2023-06-11 18:38 UTC, eyalb181 commented on mirrord/cli/src/config.rs
> +    /// Allows overiding port lock
```suggestion
    /// Allows overriding port lock
```

2023-06-11 18:38 UTC, eyalb181 commented on mirrord-schema.json
> +        "on_multi_steal": {
```suggestion
        "on_concurrent_steal": {
```

2023-06-11 18:38 UTC, eyalb181 commented on mirrord/operator/src/client.rs
> +    /// if env var is empty or missing random id will be generated and saved in exnv
Looks like a mistake

2023-06-12 17:32 UTC, Razz4780 reviewed
LGTM apart from Eyal's suggestions

2023-06-12 18:18 UTC, aviramha commented on mirrord/cli/src/main.rs
> +    if let Some(on_multi_steal) = &args.on_multi_steal {
we should stop adding more envs..

2023-06-14 06:45 UTC, aviramha commented
another thing that came to mind - we shouldn't do this if http filter is being used (i.e only "All" steal should cause this behavior)

2023-06-21 16:31 UTC, eyalb181 requested changes

2023-06-21 16:31 UTC, eyalb181 commented on mirrord-schema.json
> +      "description": "(Operator Only): Allows overiding port locks\n\nCan be set to either `\"continue\"` (default) or `\"override\"`.\n\n- `\"continue\"`: Continue with normal execution - `\"overrid
```suggestion
      "description": "(Operator Only): Allows overriding port locks.\n\nCan be set to either `\"continue\"` or `\"override\"`.\n\n- `\"continue\"`: Continue with normal execution - `\"override\"`: If port lock detected then override it with new lock and force close the original locking connection.",
```

2023-06-21 16:31 UTC, eyalb181 commented on mirrord-schema.json
> +          "description": "<!--${internal}--> ### abort\n\nAbort Execution",
```suggestion
          "description": "<!--${internal}--> ### abort\n\nAbort Execution when trying to steal traffic from a target whose traffic is already being stolen.",
```

2023-06-21 16:31 UTC, eyalb181 commented on mirrord-schema.json
> +          "description": "(Operator Only): if value of override is passed then current later will override any PortLocks and force close other connections",
current later?

2023-06-21 16:31 UTC, eyalb181 commented on mirrord/cli/src/error.rs
> +    #[error("Failed to connect to the operator. Someone else is performing network stealing on requested target")]
```suggestion
    #[error("Failed to connect to the operator. Someone else is stealing traffic from the requested target")]
```

2023-06-21 16:31 UTC, eyalb181 commented on mirrord/cli/src/error.rs
> +    There exists a port-lock on target, if you want to run anyway please set the following:
```suggestion
    If you want to run anyway please set the following:
```

2023-06-21 16:31 UTC, eyalb181 commented on mirrord/config/src/feature/network/incoming.rs
> +                on_concurrent_steal: FromEnv::new("MIRRORD_OPERATOR_ON_MULTI_STEAL")
```suggestion
                on_concurrent_steal: FromEnv::new("MIRRORD_OPERATOR_ON_CONCURRENT_STEAL")
```

2023-06-21 17:24 UTC, eyalb181 approved these changes

2023-06-21 18:31 UTC, merged