Disallow targeting crashed pods
metalbear-co/mirrord pull request #1669
Opened 2023-07-15 08:59 UTC by sploicers

Pretty small change, once I actually found the right place 😛  
Just filtering out any pod which has a PodCondition entry without "True" status (that was easiest way I could see to detect this based on just inspecting the Kube API response objects).

Apparently there is also a VS Code extension which lists targets, could expand issue scope to filtering out crashed pods there too, if that's the case?

2023-07-15 11:00 UTC, eyalb181 requested changes
Thanks! I left a few comments. Also, we actually support deployments as well - could you expand the PR to handle those? The condition should be at least one Ready pod.

By the way, the IDE extensions use `mirrord ls`, so your change would affect them automatically.

2023-07-15 23:23 UTC, sploicers commented on mirrord/cli/src/main.rs
> +                .unwrap_or(true)
Oops my bad, this would be a false positive if any of the optionals along the chain were None for whatever reason.  Thanks.

2023-07-15 23:41 UTC, sploicers commented
>  Also, we actually support deployments as well - could you expand the PR to handle those? The condition should be at least one Ready pod.

Re this, I see there's already the following check: `status.available_replicas >= Some(1)`
...and that the DeploymentStatus struct says the following about `available_replicas`:
```
/// Total number of available pods (ready for at least minReadySeconds) targeted by this deployment.
pub available_replicas: Option<i32>,
```
So, at a cursory glance this shouldn't be happening for deployments, but I will test that case and see.

2023-07-16 07:18 UTC, eyalb181 approved these changes
Disregard my comment re deployments, didn't know it was already handled there. All looks good, thanks for the contribution!

2023-07-16 09:14 UTC, merged

2023-07-17 08:34 UTC, sploicers commented
Hi again - should #1669 be closed now that my PR is merged? Maybe there's automation set up for this which I missed, based on looking for merge commits which `include` issue numbers for example? Also, I see there were some failed CI runs that I hadn't solved yet, but the PR was merged anyway. What's the process there?

2023-07-17 09:02 UTC, aviramha commented
> Hi again - should #1669 be closed now that my PR is merged? Maybe there's automation set up for this which I missed, based on looking for merge commits which `include` issue numbers for example? Also, I see there were some failed CI runs that I hadn't solved yet, but the PR was merged anyway. What's the process there?

The automatic closure happens if you write "Closes" or "Fixes" then "#issue_number".
I just closed it, thanks.
The CI runs that failed are flakes that we are unfortunate to have in our CI :(