Enable logs for mirroring(fastapi) tests
metalbear-co/mirrord pull request #1889
Opened 2023-09-02 15:38 UTC by infiniteregrets

2023-09-02 16:37 UTC, eyalb181 approved these changes

2023-09-03 06:53 UTC, eyalb181 requested changes

2023-09-03 06:53 UTC, eyalb181 commented on mirrord/layer/tests/http_mirroring.rs
> +/// NOTE: Flask, FastAPI mirroring tests are flaky and have been decorated with the flaky_test
What's the reason for the flake?

2023-09-03 15:13 UTC, infiniteregrets commented on mirrord/layer/tests/http_mirroring.rs
> +/// NOTE: Flask, FastAPI mirroring tests are flaky and have been decorated with the flaky_test
changed, please take a look

2023-09-03 15:41 UTC, eyalb181 approved these changes

2023-09-03 16:15 UTC, merged