New `completions <shell>` subcommand
metalbear-co/mirrord pull request #1949
Opened 2023-09-17 14:40 UTC by bradschwartz

Closes #1947

Adding a new subcommand for generating shell completion scripts. It can be invoked like: `mirrord completions <bash|fish|powershell|zsh|elvish>` This will make discoverability of subcommands and flags simpler for newcomers. I know Homebrew has some built-in support for calling these types of methods and installing completion scripts in the relevant places, and I see it done enough like: `source <(mirrord completions bash)` in .bashrc scripts

Everything is generated via the clap_complete crate, so should stay up to date with new options.

Currently the hidden commands are coming up in shell completions:

```bash
$ mirrord ex <TAB><TAB>
exec     extract  ext
```

Thank you for contributing to mirrord!

Please make sure you added a CHANGELOG file in `changelog.d/` named `issue_number.category.md`.
For example, `1054.changed.md` or `+towncrier.added.md` (if no issue).

2023-09-17 18:45 UTC, aviramha requested changes
Thanks for this! I've left one comment regarding the changelog file name.

2023-09-17 18:45 UTC, aviramha commented on changelog.d/1947.fixed.md
> +New subcommand for generating shell completions for bash/fish/zsh/powershell/elvish
Please change to `1947.added.md`

2023-09-17 18:49 UTC, bradschwartz commented on changelog.d/1947.fixed.md
> +New subcommand for generating shell completions for bash/fish/zsh/powershell/elvish
Just renamed 👍

2023-09-18 04:45 UTC, aviramha approved these changes

2023-09-18 04:45 UTC, aviramha commented
Great, Thank you!

2023-09-18 05:15 UTC, merged