Added new configuration 'use_proxy'
metalbear-co/mirrord pull request #2076
Opened 2023-11-21 08:13 UTC by aviramha

Added new configuration 'use_proxy' that lets user disable usage of http/s proxy by mirrord even when env is set+towncrier.added.md` (if no issue).

2023-11-21 09:27 UTC, Razz4780 requested changes
I think we should clarify semantics of this setting:
1. Are the variables no longer used by the mirrord code?
2. Are the variables no longer accessible in the user code?
3. What if the variables are present in the remote target?

2023-11-21 09:27 UTC, Razz4780 commented on mirrord/config/src/lib.rs
> +    /// ```
Leftover ```

2023-11-21 09:27 UTC, Razz4780 commented on mirrord/config/src/lib.rs
> +    /// When disabled, mirrord will remove `HTTP/S_PROXY` env variables before
```suggestion
    /// When disabled, mirrord will remove `HTTP[S]_PROXY` env variables before
```
Just a suggestion

2023-11-22 12:14 UTC, Razz4780 commented on mirrord/agent/src/steal/connection.rs
> +            stealer: TcpListener::bind((Ipv4Addr::UNSPECIFIED, 15555)).await?,
What happened here?

2023-11-22 15:27 UTC, aviramha commented on mirrord/agent/src/steal/connection.rs
> +            stealer: TcpListener::bind((Ipv4Addr::UNSPECIFIED, 15555)).await?,
crap, good catch

2023-11-23 09:51 UTC, Razz4780 approved these changes

2023-11-23 10:12 UTC, merged