Last layer refactor I promise
metalbear-co/mirrord pull request #211
Opened 2022-07-15 16:05 UTC by aviramha

- Refactored `mirrord-layer/lib.rs` - no more passsing many arguments
- Changed `addrinfo` to `VecDeque` - fixes a potential bug (loss of order)

2022-07-15 17:35 UTC, infiniteregrets commented on mirrord-layer/src/lib.rs
> +                    .unwrap();
Remove unwrap?

2022-07-15 17:37 UTC, infiniteregrets reviewed
We should probably change from unit to a result maybe

2022-07-15 17:43 UTC, aviramha commented
> We should probably change from unit to a result maybe

What do you mean?

2022-07-15 17:49 UTC, infiniteregrets commented
@aviramha 
I meant, `handle_hook_message` could probably return a Result so we can propagate errors.. and remove unwraps, not sure if that's to be done here. Sorry for not providing more context before!

2022-07-15 17:55 UTC, meowjesty requested changes
Unless I'm misunderstanding something, `Layer` doesn't need to be generic, other than that it's looking good.

2022-07-15 17:55 UTC, meowjesty commented on mirrord-layer/src/lib.rs
> +    T: tokio::io::AsyncRead + tokio::io::AsyncWrite + Unpin + Send,
Do we need this `T` generic? Don't we create only 1 type of `Layer<T>` (if you can see us needing a different `T` in the future, it's ok)?

2022-07-15 17:55 UTC, meowjesty commented on mirrord-layer/src/lib.rs
> +    fn new(codec: actix_codec::Framed<T, ClientCodec>) -> Layer<T> {
This function is only ever called once, with one type of `codec`, so I would suggest moving it to a `Default` trait implementation.

2022-07-15 18:13 UTC, meowjesty commented on mirrord-layer/src/lib.rs
> +    fn new(codec: actix_codec::Framed<T, ClientCodec>) -> Layer<T> {
Forget about this suggestion, `codec` cannot be made with default arguments, as it takes a configurable `port`.

2022-07-15 18:20 UTC, meowjesty commented on mirrord-layer/src/lib.rs
> +    T: tokio::io::AsyncRead + tokio::io::AsyncWrite + Unpin + Send,
Forgot about the pain around the `Frame(whatever)` type.

2022-07-16 07:34 UTC, aviramha commented
> @aviramha I meant, `handle_hook_message` could probably return a Result so we can propagate errors.. and remove unwraps, not sure if that's to be done here. Sorry for not providing more context before!

Yeah that can be a nice improvement but let's leave it out of scope for now and maybe let new contributors do it as it's fairly easy and not very "important"

2022-07-17 10:55 UTC, eyalb181 approved these changes

2022-07-17 10:55 UTC, eyalb181 commented on CHANGELOG.md
> +- Refactored `mirrord-layer/lib.rs` - no more passsing many arguments! :)
passing**

2022-07-17 14:08 UTC, merged