medschool: validate json snippets in config files
metalbear-co/mirrord pull request #2630
Opened 2024-08-05 05:50 UTC by infiniteregrets

closes #2525

2024-08-12 21:51 UTC, meowjesty requested changes
Thanks for the PR my bhai.

It's missing docs, overall looks fine, but I wonder why the changes to remove iterator stuff?

2024-08-12 21:51 UTC, meowjesty commented on medschool/Cargo.toml
> +serde_json = "1.0.122"
```suggestion
jsonschema = "0.18"
serde_json = "1.0"
```

We usually just use major.min everywhere else right?

2024-08-12 21:51 UTC, meowjesty commented on medschool/src/main.rs
> +    };
`if let Some {} else None` is just `.map`.

2024-08-12 21:51 UTC, meowjesty commented on medschool/src/parse.rs
> +#[tracing::instrument(level = "trace", ret)]
```suggestion
#[tracing::instrument(level = Level::TRACE, ret)]
```

For some reason we started doing it like this now.

2024-08-12 21:51 UTC, meowjesty commented on medschool/src/parse.rs
>  #[tracing::instrument(level = "trace", ret)]
```suggestion
#[tracing::instrument(level = Level::TRACE, ret)]
```

Also change it here, since you're touching this function.

2024-08-12 21:51 UTC, meowjesty commented on medschool/src/parse.rs
> +    // Maximum recursion level for safety.
```suggestion
    /// Maximum recursion level for safety.
```

2024-08-12 21:51 UTC, meowjesty commented on medschool/src/parse.rs
> +    match types.get(&field.ty) {
I don't think you need to change this so much just due to the function returning a `Result` now?

The logic inside this `match` looks very similar to the iterator (at a glance at least).

2024-08-12 21:51 UTC, meowjesty commented on medschool/src/parse.rs
> +    let mut max_area = 0;
Same thing here, the logic looks pretty much the same, except it's more `Result`-y now? You could use `try_collect` for example.

2024-08-12 23:17 UTC, infiniteregrets commented
> Thanks for the PR my bhai.
> 
> It's missing docs, overall looks fine, but I wonder why the changes to remove iterator stuff?

of course bhai, the whole closure/functional thing made the code a mess to be honest, its much easier and clear to read it with a for loop

2024-10-22 17:23 UTC, infiniteregrets commented
> Aw, I thought it would be just a matter of changing some `collect` to `try_collect`, and maybe some options to results before going into `and_then`. I asked for this because the diff felt like a bit too much, when the change is really just `validate_json_blocks(&type_.docs, schema)`.

hi, coming back to this, id like to keep the loop there just to make it more readable! will address the comments! sorry for the delay

2024-10-23 18:39 UTC, meowjesty commented
> id like to keep the loop

Alright! I'm not a `loop` person, but it was more of a suggestion due to how the bigger the diff got than what I expected.

> sorry for the delay

No worries bhai! After your previous fix the tool is already working way better.

2024-11-19 13:25 UTC, Razz4780 commented
Hey @infiniteregrets, is there any work in progress on this one?

2024-12-09 15:42 UTC, Razz4780 commented
Seems like the PR is dead :skull_and_crossbones:

2024-12-09 15:42 UTC, closed without merging