Add nodeSelector option to agent config
metalbear-co/mirrord pull request #2834
Opened 2024-10-13 15:24 UTC by dbeilin

Hello, this is my first PR so please go easy on me.
When I run `mirror exec` I missed the option to tell the agent on which node to spawn, so I added the functionality after seeing that `labels` and `annotations` were already supported (since they're more or less the same, except node selector sits under the `spec` key).

I tested it on my own cluster using this config JSON:

```json
{
  "agent": {
    "node_selector":
      {
        "node1": "label1"
      }
  }
}
```

I was interested in adding this option in the CLI too, but this seemed like a quicker proof-of-concept. If this is something you're willing to merge, I can work on the CLI version as well.

Let me know what you think 😄

2024-10-13 15:38 UTC, aviramha commented
Thanks for sending this!
We'd prefer not to expose it from cli, as we want to keep the cli api clean and concise.

2024-10-13 15:38 UTC, aviramha commented on mirrord/kube/src/api/container/job.rs
>          pod.annotations_mut().extend(annotations.clone());
run `cargo fmt --all`

2024-10-14 08:45 UTC, dbeilin commented
@aviramha Took a while to figure out the `schema_file_is_up_to_date` test. I've been fighting with with for a while until I realized my VS Code auto-saves and also auto-adds white-spaces to all files, which caused the `mirrord-schema.json` to always have a diff 😩 

Let me know if anything else is missing.

Thanks

2024-10-14 12:21 UTC, Razz4780 requested changes

2024-10-14 12:21 UTC, Razz4780 commented on mirrord/config/src/agent.rs
> +    /// Allows setting up custom node selector for the agent Job and Pod.
```suggestion
    /// Allows setting up custom node selector for the agent Pod. Applies only to targetless runs, as targeted agent always runs on the same node as its target container.
```

2024-10-14 12:21 UTC, Razz4780 commented on mirrord/kube/src/api/container/job.rs
> +
I'd move this injection to `mirrord-kube::api::container::pod::PodVariant`, so that it also works in mirrord for Teams (we don't use jobs there)

2024-10-16 07:12 UTC, merged

2024-10-28 08:16 UTC, dbeilin commented
@aviramha In addition to this PR, I believe adding the option of choosing a service account would be beneficial as well. I'm willing to give it another go and open a PR, if that's something you'd approve of.