Move some functionality to separate files
metalbear-co/mirrord pull request #31
Opened 2022-05-05 15:28 UTC by eyalb181

Move all socket management to separate file

Thank you for contributing to mirrord!

Please make sure you added a CHANGELOG entry & squashed your PR to one commit.

2022-05-05 15:48 UTC, meowjesty reviewed
👍

2022-05-05 15:48 UTC, meowjesty commented on mirrord-layer/src/sockets.rs
> +    pub fn new() -> Self {
Minor thing, if `new` takes no arguments, then it should probably be an implementation of `default` instead.

```suggestion
impl Default for Sockets {
    fn default() -> Self { ... }
}
```

2022-05-05 16:04 UTC, aviramha requested changes

2022-05-05 16:04 UTC, aviramha commented on mirrord-layer/src/sockets.rs
> +
perhaps add some docs here

2022-05-06 09:17 UTC, eyalb181 commented on mirrord-layer/src/lib.rs
> +    SOCKETS.add_port_to_connection_socket(sockfd, port);
I had some theoretical logic there (where I cached the real socket) but I'd rather run into real behaviour and then decide what to do.

2022-05-06 09:18 UTC, eyalb181 commented on mirrord-layer/src/lib.rs
> +    SOCKETS.create_connection_socket()
But it doesn't just create the socket, it also adds it to the connection sockets map, and uses it internally later

2022-05-06 09:22 UTC, eyalb181 commented on mirrord-layer/src/lib.rs
>          let os_addr: OsSocketAddr = socket_addr.into();
Implement what?

2022-05-06 14:47 UTC, aviramha commented on mirrord-layer/src/pod_api.rs
> +                    "env": [{"name": "RUST_LOG", "value": "trace"}],
RUST_LOG should be env controlled

2022-05-07 14:20 UTC, aviramha requested changes
Very good job, few last comments ;)

2022-05-07 14:20 UTC, aviramha commented on mirrord-layer/src/sockets.rs
> +    pub read_socket: SocketpairStream, /* Though this is unread, it's necessary to keep the
We actually should read it so buffers wont fill.

2022-05-07 14:20 UTC, aviramha commented on mirrord-layer/src/sockets.rs
> +    connections: Mutex<MultiMap<i32, u16, ConnectionSocket>>, // Keys are sockfd, port
You can define types so code will be more readable even without docs - 
`type SockFd = i32` `type Port = u16`

2022-05-08 17:10 UTC, aviramha commented on mirrord-layer/src/sockets.rs
> +    fn clear_data(&self, socket: &mut SocketpairStream) {
no use of self, make this a module level function

2022-05-08 17:23 UTC, aviramha approved these changes

2022-05-08 17:34 UTC, merged