Features enabled by default
metalbear-co/mirrord pull request #343
Opened 2022-09-06 13:09 UTC by DmitryDodzin

Enable by default most of the reasonable features

2022-09-06 20:00 UTC, eyalb181 requested changes
LGTM. However, we can only merge this before version 3.0.0, since it's a major API change. I'm marking this with "Request Changes" for now so we don't merge it accidentally.

2022-09-08 16:46 UTC, aviramha requested changes

2022-09-08 16:46 UTC, aviramha commented on mirrord-cli/src/config.rs
>      /// Enable udp outgoing feature.
fix comment (disable)
p.s no need to specify the long param as it's same

2022-09-08 16:46 UTC, aviramha commented on mirrord-cli/src/config.rs
> +    pub ro_fs: bool,
ro_fs should be default

2022-09-08 17:08 UTC, aviramha commented on CHANGELOG.md
> +- Change all functionality (incoming traffic mirroring, remote DNS outgoing traffic, environment variables, file reads and writes) to be enabled by default. ***Note that flags now disable functionali
file reads

2022-09-08 17:08 UTC, aviramha commented on mirrord-cli/src/config.rs
>      #[clap(long, value_parser)]
maybe switch this to enum? `--file rw/r/off`?

2022-09-08 17:27 UTC, eyalb181 requested changes

2022-09-08 17:27 UTC, eyalb181 commented on mirrord-cli/src/config.rs
> +    /// Disable file hooking (Both R/W)
Disable?

2022-09-08 17:27 UTC, eyalb181 commented on mirrord-cli/src/config.rs
> +    /// Where to extract the library to. Defaults is temp dir.
```suggestion
    /// Where to extract the library to. Default is temp dir.
```

2022-09-08 17:27 UTC, eyalb181 commented on mirrord-cli/src/main.rs
> +        warn!("Both fs flags Read/Write and disabled Writes - Disabling will take precedence");
```suggestion
        warn!("fs was both enabled and disabled - disabling will take precedence.");
```

2022-09-08 17:27 UTC, eyalb181 commented on mirrord-layer/src/file.rs
> +        r".*venv\.cfg",
Is this related to the PR?

2022-09-08 17:44 UTC, aviramha approved these changes

2022-09-08 19:44 UTC, merged