Basic Error Reporting Help
metalbear-co/mirrord pull request #629
Opened 2022-10-25 13:28 UTC by DmitryDodzin

relevant #582

2022-10-30 13:58 UTC, aviramha reviewed
LGTM.
I think we need a message for the user to check the logs being sent before uploading though.

2022-10-31 16:43 UTC, eyalb181 commented on mirrord-layer/src/lib.rs
> +    let mut layer = Layer::new(codec, config.feature.network.incoming.is_steal());
How did this sneak in here?

2022-10-31 17:53 UTC, eyalb181 requested changes

2022-10-31 17:53 UTC, eyalb181 commented on mirrord-layer/src/tracing_util.rs
> +mirrord encountered an error, please create an issue over at github, It would be much appreciated
```suggestion
mirrord encountered an error. We'd appreciate it if you could create an issue on our GitHub repository so we could address it as soon as possible.```

2022-10-31 17:53 UTC, eyalb181 commented on mirrord-layer/src/tracing_util.rs
> +NOTE: Please check and reduct the logs in the issue for sensative information. (We do love hearing feedback on how can we reduce the amount of sensative information in the logs)
```suggestion
NOTE: Please redact sensitive information from the logs.
```

2022-11-02 09:20 UTC, DmitryDodzin commented on mirrord-layer/src/lib.rs
> +    let mut layer = Layer::new(codec, config.feature.network.incoming.is_steal());
wdym?

2022-11-02 12:43 UTC, eyalb181 approved these changes

2022-11-02 13:58 UTC, DmitryDodzin commented
bors r+

2022-11-02 14:37 UTC, closed without merging