Depricated and Unstable config flags
metalbear-co/mirrord pull request #683
Opened 2022-11-03 16:31 UTC by DmitryDodzin

closes #663

2022-11-06 12:36 UTC, eyalb181 commented on mirrord/config/src/config/depricated.rs
> +pub struct Depricated<T>(String, T);
Rename to Deprecated**

2022-11-06 12:50 UTC, eyalb181 requested changes

2022-11-06 12:50 UTC, eyalb181 commented on mirrord/config/derive/README.md
> +    - `unstable` mark field as unstable and print a error message to the client
```suggestion
    - `unstable` mark field as unstable and print an error message to the user
```

2022-11-06 12:50 UTC, eyalb181 commented on mirrord/config/src/config/depricated.rs
> +    pub fn untagged(container: &'static str, attr: &'static str, inner: T) -> Self {
I don't think this should be usable without specifying a. when it will be removed and b. what should be used instead

2022-11-06 12:50 UTC, eyalb181 commented on mirrord/config/src/config/unstable.rs
> +                "Warning field {}.{} is marked as unstable, Please note api may change",
```suggestion
                "Warning: field {}.{} is marked as unstable. Please note API may change",
```

2022-11-09 15:07 UTC, eyalb181 approved these changes

2022-11-10 19:42 UTC, meowjesty commented on CHANGELOG.md
> +- mirrord-config: added `depricated` and `unstable` tags to MirrordConfg macro for messaging user when using sed fields
Typo:

```suggestion
- mirrord-config: added `deprecated` and `unstable` tags to MirrordConfg macro for messaging user when using sed (said? serde?) fields
```

2022-11-13 12:51 UTC, DmitryDodzin commented
bors r+

2022-11-13 13:22 UTC, closed without merging