Fix outdated comment
metalbear-co/mirrord pull request #708
Opened 2022-11-08 18:31 UTC by meowjesty

- Remove invalid comment from `ci.yaml`.

2022-11-08 20:49 UTC, t4lz requested changes

2022-11-08 20:49 UTC, t4lz commented on CHANGELOG.md
> +- `ci.yaml`: Remove outdated comment about mirrord schema.
In my opinion it's better not to have a changelog entry for this minor change.
I wouldn't want users that are interested what's new in the next mirrord release to read about a deleted comment in  our CI script 😁

2022-11-09 14:53 UTC, eyalb181 approved these changes

2022-11-09 20:21 UTC, t4lz approved these changes

2022-11-09 20:27 UTC, meowjesty commented
Sup bors, can you merge this?

bors r+

2022-11-09 20:58 UTC, closed without merging