CI: update homebrew formula on release
metalbear-co/mirrord pull request #723
Opened 2022-11-13 05:20 UTC by infiniteregrets

2022-11-13 17:09 UTC, eyalb181 requested changes

2022-11-13 17:09 UTC, eyalb181 commented on .github/workflows/release.yaml
> +          echo "::set-output name=version::$(grep -m 1 version Cargo.toml | cut -d' ' -f3 | tr -d '\"' | cut -d'-' -f1)"
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Now seems like a good time to migrate to the env vars, before set-output becomes more prevalent

2022-11-14 07:11 UTC, eyalb181 approved these changes

2022-11-14 16:53 UTC, infiniteregrets commented
hoping nothing is broken
bors r+

2022-11-14 16:55 UTC, closed without merging