Operator Discovery
metalbear-co/mirrord pull request #798
Opened 2022-11-29 14:20 UTC by DmitryDodzin

contains #768.

Auto discover the operator in cluster and portforward into it

2022-11-29 17:48 UTC, aviramha requested changes
Almost there!

2022-11-29 17:48 UTC, aviramha commented on mirrord-schema.json
> +        "enabeld": {
typo

2022-11-29 17:48 UTC, aviramha commented on mirrord-schema.json
> +            "string",
how does that work?

2022-11-29 17:48 UTC, aviramha commented on mirrord/cli/src/main.rs
> +    if config.operator.enabeld {
`enabled`

2022-11-29 17:48 UTC, aviramha commented on mirrord/layer/src/connection.rs
> +    } else if let Some(addr) = &config.operator.addr {
when will you be able to connect to operator like this? is this for testing purposes or user use case?

2022-11-30 11:49 UTC, DmitryDodzin commented on mirrord-schema.json
> +            "string",
removed it

2022-11-30 14:19 UTC, aviramha approved these changes
LGTM!

2022-11-30 16:10 UTC, closed without merging